plugins:
  shop_enabled:
    default: false
    client: true
  wechat_mch_id:
    default: ""
  wechat_appid:
    default: ""
  wechat_serial_no:
    default: ""
  wechat_api_v3_key:
    default: ""
  wechat_private_key_pem:
    default: ""
  wechat_platform_cert_pem:
    default: ""
  shop_default_currency:
    default: "CNY"